#!/bin/bash
#
# Run macdeployqt to create a self-contained app bundle
#
QT_BIN_DIR=$HOME/Qt5.7.0/5.7/clang_64/bin
MACDEPLOYQT=$QT_BIN_DIR/macdeployqt
RAWSTACK_APP_DIR=$(dirname $0)
RAWSTACK_APP_BUILD_DIR=$RAWSTACK_APP_DIR/../build/debug/rawstack_app
RAWSTACK_APP_BUNDLE=$RAWSTACK_APP_BUILD_DIR/rawstack.app
RAWSTACK_APP_BUNDLE_EXE_DIR=$RAWSTACK_APP_BUNDLE/Contents/MacOS
RAWSTACK_APP_QML_DIR=$RAWSTACK_APP_DIR/qml
UFRAW_EXE=$RAWSTACK_APP_BUNDLE_EXE_DIR/ufraw-batch
ENFUSE_EXE=$RAWSTACK_APP_BUNDLE_EXE_DIR/enfuse

$MACDEPLOYQT $RAWSTACK_APP_BUNDLE -verbose=3 -qmldir=$RAWSTACK_APP_QML_DIR -executable=$UFRAW_EXE -executable=$ENFUSE_EXE
